# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'atomsBlog'
tagline:          'atoms183-Blog'
description:      'A Sample blog on atoms183'
url:              'http://atoms183.github.io/'
baseurl:          ''

# Navigation
navigation:
- text: Обо мне
  url: /about/
- text: Резюме
  url: /resume/
- text: Блог
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'atoms183'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/profile.php?id=100004512194792'
flickr:
github:         'https://github.com/atoms183'
gplus:          '#'
instagram:
pinterest:
linkedin:       '#'
rss:
stackoverflow:  '#'
twitter:        '#'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
